### ISSUE TITLE
BGP path isn't switched after restart interface 

### ISSUE THREAD

**Issue by xivamar** [MERAprojects/ops-quagga#2]
## Problem Description:

After shutdown interface BGP session continues to be in Established state and route isn't switched to backup path. 
## OpenSwitch version:

OpenSwitch 0.4.0 (Build: appliance-ops-0.4.0-master-20160823125534-dev)
## Topology:

![topology](https://cloud.githubusercontent.com/assets/19854384/18004814/f33eda06-6b9e-11e6-91a5-e7124f0c7570.png)
## Steps to reproduce the problem (see attached file):
1. Configure DUTs as in attached file.
2. Check routing table and bgp routing table via `show ip route` and `show ip bgp`  on DUT1. All routes should be in the tables.
3. Ping from DUT1 loopback interface 103.0.0.1/32 on DUT3. Ping should be successful.
4. Shutdown interface 1 on DUT1.
5. Try to ping interface 103.0.0.1/32. Ping should be through interface 2. - `NOK: ping is absent. Route should be switched to backup path`.
6.  Check state of BGP sessions via `show ip bgp` command. - `NOK: session between DUT1 and DUT2 is in Established state but it should be in Idle state`.
7. No shutdown interface 1 on DUT1.
8. Try to ping interface 103.0.0.1/32. Ping should be successful. Ping should be successful.

[BGP path isn't switched after restart interface .txt](https://github.com/MERAprojects/ops-quagga/files/439278/BGP.path.isn.t.switched.after.restart.interface.txt)

**Comment by vkarpov** [comment]
Wrong description.
