### ISSUE TITLE
Some OSPF commands don't displays after restart DUT

### ISSUE THREAD

**Issue by xivamar** [MERAprojects/ops-quagga#20]
## Problem Description:

OSPF commands `area х.х.х.х stub`  and  `ip ospf priority ххх` don't displays in `show running-config` after restart DUT.
## OpenSwitch version:

OpenSwitch 1.0.0 (Build: appliance-ops-1.0.0-release+2016090200)
## Steps to reproduce the problem:
1. Configure DUTs.
2. Save config via `copy running-config startup-config`.
3. Stop all devices.
4. Start all devices.
5. Check config via `show running-config`  - NOK: `commands should be present in config`.

**Comment by mfwlarionov** [comment]
Make a correction and created pull request: https://github.com/MERAprojects/ops-quagga/pull/41

**Comment by xivamar** [comment]
Issue is fixed.
