### ISSUE TITLE
Part of bgp route-map rules disappeared after configuration

### ISSUE THREAD

**Issue by xivamar** [MERAprojects/ops-quagga#4]
## Problem Description:

Part of route-map rules disappeared after configuration
## OpenSwitch version:

OpenSwitch 0.4.0 (Build: appliance-ops-0.4.0-master-20160823125534-dev)
## Test Topology:

 ![topology](https://cloud.githubusercontent.com/assets/19854384/18053252/33e69a52-6e07-11e6-8d34-f838539587fd.png)
## Steps to reproduce the problem (see attached files):
1. Configure DUTs as in attached file.
2. Configure prefix-list and route-map on DUT1.
3. Check our config via `show running-config`. - NOK: `Rules match ip address prefix-list LocPrf1_IN and match ip address prefix-list LocPrf2_IN are absent.`
4. Restart neighbors on DUT1.
5. Check bgp routing table via `show ip bgp` on DUT1. Only values of LocPrf=50 were applied. 

[Part of route-map rules disappeared after configuration.txt](https://github.com/MERAprojects/ops-quagga/files/442569/Part.of.route-map.rules.disappeared.after.configuration.txt)

**Comment by vkarpov** [comment]
The fault not reproduced on the dill.
