### ISSUE TITLE
 IPv6 static routes are not displayed in 'show ipv6 route' command 

### ISSUE THREAD

**Issue by xivamar** [MERAprojects/ops-quagga#6]
## Problem Description:

Active IPv6 static routes are not displayed in 'show ipv6 route' command output.
## OpenSwitch version:

OpenSwitch 0.4.0 (Build: appliance-ops-0.4.0-master-20160823125534-dev)
## Test Topology:

```
      DUT3 
     /    \
 DUT2 --- DUT4
    \      /
      DUT1
```
## Steps to reproduce the problem (see attached file):
1. Configure ipv6 addresses on each DUTs. Add static route to 2002::6600:8/126 network on DUT1.
2. Check routing table via `show ipv6 route` on DUT1. - `NOK: the route to 2002::6600:8/126 network is absent`
3. Check rib table via `show rib`. All routes should be in the tables (static route is present).
4. Ping from DUT1 interface 2002::6600:9/126 on DUT4. Ping should be successful.

[IPv6 static routes are not displayed in 'show ipv6 route' command .txt](https://github.com/MERAprojects/ops-quagga/files/444142/IPv6.static.routes.are.not.displayed.in.show.ipv6.route.command.txt)

**Comment by ekgrish** [comment]
Issue doesn't reproduce

related with: 
IPv6 static routes aren't configured https://github.com/MERAprojects/ops-build/issues/8 
Revert "Merge branch 'meraswitch/devel/full_notation_ipv6_addr' into … #39
