### ISSUE TITLE
IPv6 address in full and CIDR notation is perceived as different ip-addresses

### ISSUE THREAD

**Issue by xivamar** [MERAprojects/ops-quagga#7]
## Problem Description:

We can configure 2 same active static routes (in normal notation and in CIDR notation). 
## OpenSwitch version:

OpenSwitch 0.4.0 (Build: appliance-ops-0.4.0-master-20160823125534-dev)
## Test Topology:

```
      DUT3 
     /    \
 DUT2 --- DUT4
    \      /
      DUT1
```
## Steps to reproduce the problem (see attached file):
1. Configure ipv6 addresses on each DUTs as in attached file. 
2. Add static route with 2002:0:0:0:0:0:6500:1 nexthop to 2002::6600:8/126 network on DUT1.
3. Try to add static route with 2002::6500:1 nexthop to 2002::6600:8/126 network on DUT1. - `NOK: Error message`Nexthop already exists`should be returned`.
4. Check config via `show running-config` and `show rib`.  - `NOK: Config contains 2 same static routes`.

[Two active static routes with identical nexthop .txt](https://github.com/MERAprojects/ops-quagga/files/444191/Two.active.static.routes.with.identical.nexthop.txt)

**Comment by xivamar** [comment]
Also same problem is present in BGP: if BGP neighbors were configured with IPv6 address in full notation , session between neighbors will not Established.

**Comment by stroykov** [comment]
https://github.com/MERAprojects/ops-quagga/pull/31
